
Vagrant.configure("2") do |config|

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  config.vm.synced_folder "../", "/home/vagrant/openvpn-client"
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "openvpn"

  # Defaults for all boxes
  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.memory = "1024"
  end


  config.vm.provision "shell", path: "./config.sh", args: ["7", "bionic"]

end
